# Columms  having differnt formats

In [1]:
import pandas as pd

In [2]:
bed_room={"bhk":["2 BHK","3 Bedroom","2 bhk"]}

In [3]:
my_data=pd.DataFrame(bed_room)

In [4]:
my_data

         bhk
0      2 BHK
1  3 Bedroom
2      2 bhk

In [5]:
lit=[]

In [6]:
for i in range(0,3):
    ouput=my_data["bhk"][i].split(' ')
    lit.append(ouput[0])

In [7]:
lit

['2', '3', '2']

In [8]:
my_data["no of Bedrooms"]=lit

In [9]:
my_data

         bhk no of Bedrooms
0      2 BHK              2
1  3 Bedroom              3
2      2 bhk              2

In [10]:
house={"bedroom":["2 BHK","2 bHK","2 bhk"]}

In [11]:
house_data=pd.DataFrame(house)

In [12]:
house_data

  bedroom
0   2 BHK
1   2 bHK
2   2 bhk

In [13]:
bedroom_list=[]
for i in range(0,3):
    bedroom=house_data["bedroom"][i].upper()  #lower
    bedroom_list.append(bedroom)

In [14]:
bedroom_list

['2 BHK', '2 BHK', '2 BHK']

In [15]:
data_scientist=pd.read_csv(r"C:\Users\venuk\OneDrive\Desktop\assignment\DataScientist.csv")

In [16]:
data_scientist.head()

,Unnamed: 0,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,0,0,Senior Data Scientist,$111K-$181K (Glassdoor est.),"ABOUT HOPPER\n\nAt Hopper, weâ€™re on a mission ...",3.5,Hopper\n3.5,"New York, NY","Montreal, Canada",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,-1,-1
1,1,1,"Data Scientist, Product Analytics",$111K-$181K (Glassdoor est.),"At Noom, we use scientifically proven methods ...",4.5,Noom US\n4.5,"New York, NY","New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,-1,-1
2,2,2,Data Science Manager,$111K-$181K (Glassdoor est.),Decode_M\n\nhttps://www.decode-m.com/\n\nData ...,-1.0,Decode_M,"New York, NY","New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,-1,True
3,3,3,Data Analyst,$111K-$181K (Glassdoor est.),Sapphire Digital seeks a dynamic and driven mi...,3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ","Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Zocdoc, Healthgrades",-1
4,4,4,"Director, Data Science",$111K-$181K (Glassdoor est.),"Director, Data Science - (200537)\nDescription...",3.4,United Entertainment Group\n3.4,"New York, NY","New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"BBDO, Grey Group, Droga5",-1

In [17]:
data_scientist["Salary Estimate"].value_counts()

$93K-$151K (Glassdoor est.)         62
$113K-$180K (Glassdoor est.)        61
$111K-$175K (Glassdoor est.)        60
$71K-$122K (Glassdoor est.)         60
$119K-$147K (Glassdoor est.)        44
                                    ..
$114K-$185K (Glassdoor est.)         7
$99K-$173K (Glassdoor est.)          6
$146K-$175K (Glassdoor est.)         3
$10-$26 Per Hour(Glassdoor est.)     3
$41K-$74K (Glassdoor est.)           1
Name: Salary Estimate, Length: 148, dtype: int64

In [18]:
filter=[]
for i in range(0,3909):
    output=data_scientist["Salary Estimate"][i].split('(',1)
    filter.append(output[0])

In [19]:
filter[1:5]      #removed (GlassDoor est.)

['$111K-$181K ', '$111K-$181K ', '$111K-$181K ', '$111K-$181K ']

In [20]:
data_scientist["filter_salary"]=filter

In [21]:
data_scientist.head()

,Unnamed: 0,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,filter_salary
0,0,0,Senior Data Scientist,$111K-$181K (Glassdoor est.),"ABOUT HOPPER\n\nAt Hopper, weâ€™re on a mission ...",3.5,Hopper\n3.5,"New York, NY","Montreal, Canada",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,-1,-1,$111K-$181K
1,1,1,"Data Scientist, Product Analytics",$111K-$181K (Glassdoor est.),"At Noom, we use scientifically proven methods ...",4.5,Noom US\n4.5,"New York, NY","New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,-1,-1,$111K-$181K
2,2,2,Data Science Manager,$111K-$181K (Glassdoor est.),Decode_M\n\nhttps://www.decode-m.com/\n\nData ...,-1.0,Decode_M,"New York, NY","New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,-1,True,$111K-$181K
3,3,3,Data Analyst,$111K-$181K (Glassdoor est.),Sapphire Digital seeks a dynamic and driven mi...,3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ","Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Zocdoc, Healthgrades",-1,$111K-$181K
4,4,4,"Director, Data Science",$111K-$181K (Glassdoor est.),"Director, Data Science - (200537)\nDescription...",3.4,United Entertainment Group\n3.4,"New York, NY","New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"BBDO, Grey Group, Droga5",-1,$111K-$181K

In [22]:
##Per Hour

In [23]:
filter_1=[]
for i in range(0,3909):
    output=data_scientist["filter_salary"][i].replace('Per Hour',"")
    filter_1.append(output)

In [24]:
filter_1[:5]

['$111K-$181K ',
 '$111K-$181K ',
 '$111K-$181K ',
 '$111K-$181K ',
 '$111K-$181K ']

In [25]:
data_scientist["filter_salary"]=filter_1
data_scientist["filter_salary"].head()

0    $111K-$181K
1    $111K-$181K
2    $111K-$181K
3    $111K-$181K
4    $111K-$181K
Name: filter_salary, dtype: object

In [26]:
filter_2=[]
for i in range(0,3909):
    output=data_scientist["filter_salary"][i].replace('K',"")
    filter_2.append(output)

In [27]:
filter_2

['$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$111-$181 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$120-$140 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$74-$124 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$102-$121 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$129-$210 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$156-$254 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$119-$147 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$116-$152 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$133-$171 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$110-$139 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$82-$141 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$96-$119 ',
 '$146-$175 ',
 '$146-$175 ',
 '$146-$175 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$102-$164 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$113-$180 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$76-$122 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$134-$218 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$76-$125 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$132-$208 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$83-$105 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$75-$143 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$34-$72 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$37-$75 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$113-$184 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$136-$164 ',
 '$34-$53 ',
 '$34-$53 ',
 '$34-$53 ',
 '$34-$53 ',
 '$34-$53 ',
 '$34-$53 ',
 '$34-$53 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$46-$80 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$79-$130 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$91-$105 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$31-$56 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$39-$81 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$99-$174 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$76-$147 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$62-$109 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$70-$123 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$40-$73 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$38-$59 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 '$60-$105 ',
 ...]

In [28]:
data_scientist["filter_salary"]=filter_2
data_scientist["filter_salary"].head()

0    $111-$181
1    $111-$181
2    $111-$181
3    $111-$181
4    $111-$181
Name: filter_salary, dtype: object

In [29]:
filter_3=[]
for i in range(0,3909):
    output=data_scientist["filter_salary"][i].replace('$',"")
    filter_3.append(output)

In [30]:
filter_3[:5]

['111-181 ', '111-181 ', '111-181 ', '111-181 ', '111-181 ']

In [31]:
data_scientist["filter_salary"]=filter_3
data_scientist["filter_salary"].head()

0    111-181
1    111-181
2    111-181
3    111-181
4    111-181
Name: filter_salary, dtype: object

In [32]:
low=[]
high=[]
for i in range(0,3909):
    output=data_scientist["filter_salary"][i].split('-',1)
    low.append(output[0])
    high.append(output[1])

In [33]:
low[:5]

['111', '111', '111', '111', '111']

In [34]:
high[:5]

['181 ', '181 ', '181 ', '181 ', '181 ']

In [35]:
data_scientist["low"]=low
data_scientist["high"]=high

In [36]:
data_scientist.head()

,Unnamed: 0,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,filter_salary,low,high
0,0,0,Senior Data Scientist,$111K-$181K (Glassdoor est.),"ABOUT HOPPER\n\nAt Hopper, weâ€™re on a mission ...",3.5,Hopper\n3.5,"New York, NY","Montreal, Canada",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,-1,-1,111-181,111,181
1,1,1,"Data Scientist, Product Analytics",$111K-$181K (Glassdoor est.),"At Noom, we use scientifically proven methods ...",4.5,Noom US\n4.5,"New York, NY","New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,-1,-1,111-181,111,181
2,2,2,Data Science Manager,$111K-$181K (Glassdoor est.),Decode_M\n\nhttps://www.decode-m.com/\n\nData ...,-1.0,Decode_M,"New York, NY","New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,-1,True,111-181,111,181
3,3,3,Data Analyst,$111K-$181K (Glassdoor est.),Sapphire Digital seeks a dynamic and driven mi...,3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ","Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Zocdoc, Healthgrades",-1,111-181,111,181
4,4,4,"Director, Data Science",$111K-$181K (Glassdoor est.),"Director, Data Science - (200537)\nDescription...",3.4,United Entertainment Group\n3.4,"New York, NY","New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"BBDO, Grey Group, Droga5",-1,111-181,111,181